name: "Flare-Prerelease"
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
jobs:
  pre-ci:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: 'Block Concurrent Executions'
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 10
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}

  Bump-Prerelease-Flare-Publish:
    name: Bump-Prerelease-Flare-Publish
    needs: pre-ci
    if: "!startsWith(github.event.head_commit.message, '[SKIP CI]') && !startsWith(github.event.head_commit.message, '[release]') && github.repository == 'subquery/subql-ethereum'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 100
          token: ${{ secrets.REPO_TOKEN }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: marceloprado/has-changed-path@v1
        id: changed-types-flare
        with:
          paths: packages/types

      - uses: marceloprado/has-changed-path@v1
        id: changed-common-flare
        with:
          paths: packages/common-ethereum

      - uses: marceloprado/has-changed-path@v1
        id: changed-node
        with:
          paths: packages/node

      #Changes packages names
      - name: Change common ethereum to flare
        uses: jaywcjlove/github-action-package@main
        with:
          path: packages/common-ethereum/package.json
          rename: '@subql/common-flare'

      - name: Change types ethereum to flare
        uses: jaywcjlove/github-action-package@main
        with:
          path: packages/types/package.json
          rename: '@subql/types-flare'

      - name: Change node ethereum to flare
        uses: jaywcjlove/github-action-package@main
        with:
          path: packages/node/package.json
          rename: '@subql/node-flare'

      #update imports

      - run: chmod +x ./.github/workflows/scripts/update_flare_imports.sh

      - name: Update imports to flare
        run: ./.github/workflows/scripts/update_flare_imports.sh

      - run: yarn

      - name: build
        run: yarn workspaces foreach run build

      #Add remove-stable-version
      - name: Bump types flare & deploy
        if: steps.changed-types-flare.outputs.changed == 'true'
        uses: ./.github/actions/create-prerelease
        with:
          package-path: packages/types
          npm-token: ${{ secrets.NPM_TOKEN }}

      - name: Bump common flare & deploy
        if: steps.changed-common-flare.outputs.changed == 'true'
        uses: ./.github/actions/create-prerelease
        with:
          package-path: packages/common-ethereum
          npm-token: ${{ secrets.NPM_TOKEN }}

      - name: Bump node & deploy
        if: steps.changed-node.outputs.changed == 'true'
        uses: ./.github/actions/create-prerelease
        with:
          package-path: packages/node
          npm-token: ${{ secrets.NPM_TOKEN }}
